version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: job-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: job_management_system
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"  # 기존 로컬 DB와 포트 충돌 방지
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - job-management-network

  # 추후 백엔드 추가 예정
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/job_management_system
  #   networks:
  #     - job-management-network

volumes:
  mysql_data:

networks:
  job-management-network:
    driver: bridge
